- name: dependency ffmpeg
  yum:
    state: latest
    name:
      - autoconf
      - automake
      - cmake
      - freetype-devel
      - gcc
      - gcc-c++
      - libtool
      - make
      - mercurial
      - patch
      - pkgconfig
      - zlib-devel

- name: install yasm
  yum: name=yasm

- name: install nasm
  yum: name=nasm

- name: install x264
  yum:
    name:
      - http://pkgrepo.linuxtech.net/el6/release/x86_64/x264-0.130-0.20130531.1.el6.x86_64.rpm
      - http://pkgrepo.linuxtech.net/el6/release/x86_64/libx264_130-0.130-0.20130531.1.el6.x86_64.rpm
      - http://pkgrepo.linuxtech.net/el6/release/x86_64/libx264-devel-0.130-0.20130531.1.el6.x86_64.rpm

- name: install x265 & numactl-devel
  yum:
    name:
      - http://li.nux.ro/download/nux/dextop/el6/x86_64/x265-libs-1.9-1.el6.nux.x86_64.rpm
      - http://li.nux.ro/download/nux/dextop/el6/x86_64/x265-1.9-1.el6.nux.x86_64.rpm
      - http://li.nux.ro/download/nux/dextop/el6/x86_64/x265-devel-1.9-1.el6.nux.x86_64.rpm
      - numactl-devel

- name: install fdk-aac
  yum:
    name:
      - http://li.nux.ro/download/nux/dextop/el7/x86_64/fdk-aac-0.1.4-1.x86_64.rpm
      - http://li.nux.ro/download/nux/dextop/el6/x86_64/fdk-aac-devel-0.1.4-1.x86_64.rpm

- name: install lame
  yum:
    name:
      - http://dl.fedoraproject.org/pub/epel/6/x86_64/Packages/l/lame-libs-3.100-1.el6.x86_64.rpm
      - http://dl.fedoraproject.org/pub/epel/6/x86_64/Packages/l/lame-3.100-1.el6.x86_64.rpm
      - http://dl.fedoraproject.org/pub/epel/6/x86_64/Packages/l/lame-devel-3.100-1.el6.x86_64.rpm

- name: install opus
  yum:
    name:
      - http://dl.fedoraproject.org/pub/epel/6/x86_64/Packages/o/opus-1.1.3-2.el6.x86_64.rpm
      - http://dl.fedoraproject.org/pub/epel/6/x86_64/Packages/o/opus-devel-1.1.3-2.el6.x86_64.rpm

- name: install libogg
  yum: name=libogg

- name: install libvorbis
  yum:
    name:
      - libvorbis
      - libvorbis-devel

- name: install libvpx
  yum:
    name:
      - http://dl.fedoraproject.org/pub/fedora/linux/releases/28/Everything/x86_64/os/Packages/l/libvpx-1.7.0-5.fc28.x86_64.rpm
      - http://dl.fedoraproject.org/pub/fedora/linux/releases/28/Everything/x86_64/os/Packages/l/libvpx-devel-1.7.0-5.fc28.x86_64.rpm

- name: install cmake3
  yum: name=cmake3

- name: install aom
  yum:
    name:
      - http://dl.fedoraproject.org/pub/fedora/linux/updates/28/Everything/x86_64/Packages/l/libaom-1.0.0-4.20180925gitd0076f5.fc28.x86_64.rpm
      - http://dl.fedoraproject.org/pub/fedora/linux/updates/28/Everything/x86_64/Packages/a/aom-1.0.0-4.20180925gitd0076f5.fc28.x86_64.rpm
      - http://dl.fedoraproject.org/pub/fedora/linux/updates/28/Everything/x86_64/Packages/l/libaom-devel-1.0.0-4.20180925gitd0076f5.fc28.x86_64.rpm

- name: copy libaomenc.c patch
  copy:
     src: libaomenc.patch
     dest: /usr/local/src/libaomenc.patch
     owner: root
     group: root
     mode: 0744

- name: install ffmpeg ffmpeg
  shell: |
    echo "ffmpeg"
    mkdir -p $HOME/bin
    cd /usr/local/src
    wget http://ffmpeg.org/releases/ffmpeg-4.0.2.tar.xz
    tar Jxfv ffmpeg-4.0.2.tar.xz
    cd ffmpeg-4.0.2
    patch -f ./libavcodec/libaomenc.c /usr/local/src/libaomenc.patch | true
    PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure --prefix="$HOME/ffmpeg_build" --extra-cflags="-I$HOME/ffmpeg_build/include" --extra-ldflags="-L$HOME/ffmpeg_build/lib" --bindir="/usr/bin" --pkg-config-flags="--static" --enable-gpl --enable-nonfree --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libaom --extra-libs=-lpthread --extra-libs=-lm
    make
    make install
    hash -r
  args:
    creates: /usr/bin/ffmpeg
